[package]
name = "gloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.5.1"
cocoon = "0.4.1"
crossterm = "0.27.0"
hex = "0.4.3"
rpassword = "7.3.1"
totp-rs = "5.5.1"
zeroize = "1.7.0"
